- name: Instalar Containerd e Kubernetes
  hosts: all
  roles:
    - containerd
    - kubernetes

- name: Configurar ControlPlane
  hosts: control
  roles:
    - control

- name: Configurar Worker
  hosts: worker
  roles:
    - worker

