- name: Instalar Containerd e Kubernetes
  hosts: all
  roles:
    - containerd
    - kubernetes

- name: Configurar Primeiro ControlPlane
  hosts: master
  roles:
    - master

- name: Configurar Demais ControlPlanes
  hosts: control
  roles:
    - control

- name: Configurar Workers
  hosts: worker
  roles:
    - worker