---
  - name: Baixar as imagens do Kubernetes
    ansible.builtin.shell: sudo kubeadm config images pull

  - name: Inicializar o Cluster
    ansible.builtin.shell: kubeadm init --ignore-preflight-errors=NumCPU --control-plane-endpoint "{{ ansible_host}}:6443" --upload-certs --apiserver-cert-extra-sans={{ ansible_host}} --pod-network-cidr=10.244.0.0/16

  - name: Get Join Command
    ansible.builtin.shell: kubeadm token create --print-join-command
    register: token

  - name: Linha de comando para Incluir Nós no Cluster
    ansible.builtin.debug:
      msg: "{{ token.stdout_lines[0] }}"

  - name: Exportar Variavel para Nodes
    ansible.builtin.add_host:
      name: control
      join_cluster: "{{ token.stdout_lines[0] }}"

  - name: Kubeconfig para o usuario ubuntu e root
    ansible.builtin.shell: |
      mkdir -p /home/ubuntu/.kube
      mkdir -p /root/.kube
      cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config  
      cp /etc/kubernetes/admin.conf /root/.kube/config  
      chown ubuntu.ubuntu /home/ubuntu/.kube/config

  - name: Configuracao do CNI
    ansible.builtin.shell: kubectl apply -f "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"

  - name: Visualizar Kubeconfig remoto
    ansible.builtin.shell: cat /etc/kubernetes/admin.conf
    register: kubeconfig

  - name: Copiar Kubeconfig para localhost
    ansible.builtin.shell: echo "{{ kubeconfig.stdout }}" > ./config
    delegate_to: localhost


