---
  - name: Adicionar repositorio helm
    ansible.builtin.shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

  - name: Instalar o nfs-subdir-external-provisioner
    ansible.builtin.shell: |
      helm upgrade --install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ nfsserver }} --set nfs.path={{ nfspath }} --set storageClass.reclaimPolicy=Retain --create-namespace -n nfs-provisioner
