---
  - name: Adicionando Chave GPG do Kubernetes
    ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      state: present
      keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Adicionando Repositorio do Kubernetes
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
      state: present
      filename: kubernetes

  - name: Criação do Arquivo de Configuração dos Modulos do Kernel para o K8s
    ansible.builtin.file:
      path: /etc/modules-load.d/k8s.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Configurar os Modulos do Kernel para o K8s
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter
        nf_nat
        xt_REDIRECT
        xt_owner
        iptable_nat
        iptable_mangle
        iptable_filter

  - name: Criação do Arquivo de Configuração do Sysctl para o K8s
    ansible.builtin.file:
      path: /etc/sysctl.d/k8s.conf
      state: touch
      mode: u=rw,g=r,o=r

  - name: Mais configuracoes para o Kubernetes
    ansible.builtin.blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1

  - name: Desabiltar o Swap
    ansible.builtin.command: swapoff -a

  - name: Instalar o Kubernetes
    ansible.builtin.apt:
      name:
      - kubelet
      - kubeadm
      - kubectl
      state: present

  - name: Habilita Serviço Kubelet
    ansible.builtin.systemd:
      name: kubelet
      enabled: true

  - name: Reboot
    ansible.builtin.reboot: 
      reboot_timeout: 120

  - name: Resetar Regras de Firewall
    ansible.builtin.shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
