---
  - name: Adicionando Chave GPG do Docker ContainerD
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.gpg

  - name: Verificando arquitetura
    ansible.builtin.shell: dpkg --print-architecture
    register: architecture

  - name: Adicionando Repositorio do Docker ContainerD
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Instalar Dependencias
    ansible.builtin.apt:
      name: 
        - vim
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg 
        - lsb-release 
        - nfs-common 
        - chrony
      state: present
      update_cache: yes


  - name: Instalar Containerd
    ansible.builtin.apt:
      name: containerd.io
      state: present
      update_cache: yes
  
  - name: Criar o arquivo de configuração do Containerd
    ansible.builtin.shell:
      cmd: containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  
  - name: Ajuste arquivo Containerd
    ansible.builtin.shell:
      cmd: sudo sed -i 's|SystemdCgroup = false|SystemdCgroup = true|g' /etc/containerd/config.toml

  - name: Habilita Serviço Containerd
    ansible.builtin.systemd:
      name: containerd
      enabled: true